### ISSUE TITLE
Difference from Veloren?

### ISSUE THREAD

**Issue by linonetwo** [ill-inc/biomes-game#42]
The felling looks very simillar to https://github.com/veloren/veloren , can you show the difference of gameplay and roadmap?

Anyway, very appreciate the MIT license! This will make the Minecraft-like game's "biome" blooms!

**Comment by DevinLeamy** [comment]
Hey! The differences between games like Minecraft and Veloren, and Biomes are best illustrated by the gameplay itself. We've included the trailer and links to Twitch streams of Biomes in the [game's docs](https://docs.biomes.gg/gameplay). 

Biomes' roadmap is still TBD and will largely depend on what the community wants!

**Comment by linonetwo** [comment]
Great, maybe you can enable Discussion in this repo so questions can be there...

**Comment by DevinLeamy** [comment]
> Discussion

Solid idea! In the mean time I'd suggest checking out our community Discord at https://discord.gg/biomes!
