### ISSUE TITLE
Update player ECS data from the admin view

### ISSUE THREAD

**Issue by DevinLeamy** [ill-inc/biomes-game#48]
### Overview
We currently do not have a way to update player ECS data from the admin view (`/admin`). This would be useful so we could more easily fix players in broken game states.

### Ideal Solution
A new page `/admin/ecs-state-editor` that allows you to view and update a player's ECS values. This could start as simple as something for editing _just_ the player's position.

**Comment by Sanyam-jain30** [comment]
I am interested in this issue. Please assign it to me.

**Comment by DevinLeamy** [comment]
Deployed.
