### ISSUE TITLE
Would you guys consider doing a VDP?

### ISSUE THREAD

**Issue by R-Rothrock** [ill-inc/biomes-game#69]
Of course, not until the thing is up and running. I understand you guys are open sourced, but apparently you've got OpenAI backing, so...

**Comment by DevinLeamy** [comment]
Hi @R-Rothrock. Not sure what you mean by VDP?

**Comment by R-Rothrock** [comment]
Vulnerability disclosure program. Not sure if this is the place to mention such a thing...

**Comment by DevinLeamy** [comment]
> Vulnerability disclosure program. Not sure if this is the place to mention such a thing...

Gotcha. It's not a bad idea, but as of now there are no plans set that up. If you have found a vulnerability I'd recommend disclosing it privately to someone on the dev team. Our community Discord is https://discord.gg/biomes.

Feel free to shoot me (devinleamy on Discord) a message.
