### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by HeroaDev** [ill-inc/biomes-game#90]
error /home/ubuntu/biomes-game/node_modules/segfault-handler: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/ubuntu/biomes-game/node_modules/segfault-handler
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.15.0 | linux | x64
gyp info find Python using Python version 3.10.14 found at "/home/ubuntu/biomes-game/.venv/bin/python3"

gyp info spawn /home/ubuntu/biomes-game/.venv/bin/python3
gyp info spawn args [
gyp info spawn args '/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/ubuntu/biomes-game/node_modules/segfault-handler/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/ubuntu/.cache/node-gyp/20.15.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/20.15.0',
gyp info spawn args '-Dnode_gyp_dir=/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/20.15.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/ubuntu/biomes-game/node_modules/segfault-handler',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 6.8.0-1009-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v20.15.0/bin/node" "/home/ubuntu/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/biomes-game/node_modules/segfault-handler
gyp ERR! node -v v20.15.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok

**Comment by kochetkovpavlo** [comment]
@HeroaDev , seems you didn't install make.

**Comment by HeroaDev** [comment]
I installed make and g++, not it works for me. Thanks @kochetkovpavlo
